name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
    build:
        name: Build & Unit Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: hello world
              run: |
                echo 'Hello World!'
                echo 'upload ${{github.sha}}' > record.txt
                echo 'event: ${{ github.event_name }}, ref: ${{github.ref}}, head_ref: ${{github.head_ref}}, base_ref: ${{github.base_ref}}'

            - name: save build artifact
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              uses: actions/upload-artifact@v2
              with: 
                name: record-file
                path: record.txt


    deploy:
        needs: [build]
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        name: Auto Deploy
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v2
              with:
                name: record-file
                path: record-download.txt

            - name: display record file
              run: cat record-download.txt

            - name: upload artifact
              run: |
                echo "Upload Artifact Successful"
